### ISSUE TITLE
ECHO's efficiency in detecting "sawtooth" and non-symmetrical rhythms compared to RAIN

### ISSUE THREAD

**Issue by JenW1984** [delosh653/ECHO#2]
I'm looking at the RAIN paper (Thaben and Westermark, 2014) and it is saying that it is good at detecting sawtooth shaped rhythms and non-symmetric wave forms. From their paper, they mention "the case of an initial increase and a subsequent decrease". The paper also mentions a rhythms with a "steep rise and slow decay or vice versa". I have yet to try it on my data and compare to ECHO, but it seems to me that ECHO would also be able to detect these rhythms. Are you familiar with RAIN's methodology and if so what are your thoughts on how efficient ECHO would be in detecting these types of rhythms.

**Comment by delosh653** [comment]
Hi JenW1984! While ECHO hasn't been explicitly tested against sawtooth-shaped rhythms, I would expect that ECHO would do reasonably well in detecting them -- it's pretty robust, even if the rhythm isn't similar to a cosine wave.

Since this isn't really an issue, I'm going to close it, but if you have any more thoughts/questions on this subject, please use the contact information in the README for a more prompt response.

**Comment by bennek2** [comment]
Hi Hannah,

Hope all is well. Enjoying my bound copy of of your thesis.  Hope life is treated you well in Boston.

Best,
Kristin

On May 3, 2021, at 8:47 PM, Hannah De los Santos ***@***.******@***.***>> wrote:



Hi JenW1984! While ECHO hasn't been explicitly tested against sawtooth-shaped rhythms, I would expect that ECHO would do reasonably well in detecting them -- it's pretty robust, even if the rhythm isn't similar to a cosine wave.

Since this isn't really an issue, I'm going to close it, but if you have any more thoughts/questions on this subject, please use the contact information in the README for a more prompt response.
