### ISSUE TITLE
Error: task 41 failed

### ISSUE THREAD

**Issue by devang-mehta** [delosh653/ECHO#3]
Hi, I keep obtaining the following error when I try to run the App. Do you have any idea what the problem might be?

Listening on http://127.0.0.1:3236
[1] "Beginning to run ECHO..."
[1] "Started on: 2021-08-11 11:03:17"
[1] "Percentage finished out of 4168 expressions:"
  |================================================================================================================| 100%Warning: Error in {: task 41 failed - "evaluation of fn function returns non-sensible value!"
  [No stack trace available]

**Comment by delosh653** [comment]
Hi, Devang. No, I do not know what this issue is -- it is likely a data source issue. Please make sure to check several of the fixes in the FAQ and all help text encoded in the application. If those don't resolve the issue (and post here if they do), please follow the guidelines for submitting bugs.
